#!/bin/bash

#SBATCH --mail-type=fail
#SBATCH --job-name="clean_up_reads"
#SBATCH --nodes=1
#SBATCH --cpus-per-task=4
#SBATCH --time=2:00:00
#SBATCH --mem=25G
#SBATCH --partition=pibu_el8

#save read directory and intended output directory as variables
READS_DIR=/data/courses/rnaseq_course/toxoplasma_de/reads
OUT_DIR=/data/users/${USER}/rna_seq/cleaned_fastqc

#source trimmomatic, source stolen from bioinformatic course SBC07107
#source /data/users/lfalquet/SBC07107_23/scripts/module.sh
#possibly 
module load trimmomatic/trimmomatic-0.35.jar

#move to project directory and create output directory
cd /data/users/${USER}/rna_seq
mkdir ${OUT_DIR}

#remove overrepresented sequences and trim reads
trimmomatic SE -phred33 -threads 4 ${READS_DIR}SRR*.fastq.gz ${OUT_DIR}/SRR*_cleaned.fastq.gz ILLUMINACLIP:TruSeq3-SE:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:50

#execute fastqc for the cleaned reads 
apptainer exec --bind ${OUT_DIR} ${CONTAINER} \
fastqc \
--outdir ${OUT_DIR} \
"$OUT_DIR"/SRR*_cleaned.fastq.gz

#summarise results with multiqc
#singularity exec --bind . /software/singularity/containers/MultiQC-1.11-1.ubuntu20.sif multiqc .
