#!/bin/bash

#SBATCH --mail-type=fail
#SBATCH --job-name="fastp"
#SBATCH --nodes=1
#SBATCH --cpus-per-task=8
#SBATCH --time=1:00:00
#SBATCH --mem=25G
#SBATCH --partition=pibu_el8

#save read- , intended output- and container directory as variables
READS_DIR=/data/courses/rnaseq_course/toxoplasma_de/reads

CONTAINER=/containers/apptainer/fastp_0.23.2--h5f740d0_3.sif

OUT_DIR=/data/users/${USER}/rna_seq/cleaned_fastp

#read in File number from command line argument
FILE_NUMBER=$1

#move to project directory and create output directory
cd /data/users/${USER}/rna_seq
mkdir ${OUT_DIR}

#cleaning up using fastp
apptainer exec --bind ${READS_DIR} ${CONTAINER} fastp -D -p -g -x -i ${READS_DIR}/SRR${FILE_NUMBER}_1.fastq.gz -I ${READS_DIR}/SRR${FILE_NUMBER}_2.fastq.gz  -o ${OUT_DIR}/SRR${FILE_NUMBER}_1_cleaned.fastq.gz -O ${OUT_DIR}/SRR${FILE_NUMBER}_2_cleaned.fastq.gz
