#!/bin/bash

#SBATCH --mail-type=fail
#SBATCH --job-name="get_assembly_annotation"
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=00:30:00
#SBATCH --mem=1G
#SBATCH --partition=pibu_el8

#move to fastqc results directory
cd /data/users/${USER}/rna_seq/fastqc

#get reference genome
wget ftp://ftp.ensembl.org/pub/release-113/fasta/mus_musculus/dna/Mus_musculus.GRCm39.dna.primary_assembly.fa.gz
wget ftp://ftp.ensembl.org/pub/release-113/gtf/mus_musculus/Mus_musculus.GRCm39.113.gtf.gz