#!/bin/bash

#SBATCH --mail-type=fail
#SBATCH --job-name="indexing"
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=04:00:00
#SBATCH --mem=8G
#SBATCH --partition=pibu_el8

INPUT_DIR=/data/courses/rnaseq_course/toxoplasma_de/reads
HISAT2_DIR=/containers/apptainer/hisat2_samtools_408dfd02f175cd88.sif

apptainer exec --bind $INPUT_DIR $HISAT2_DIR hisat2-build Mus_musculus.GRCm39.dna.primary_assembly.fa.gz