#!/bin/bash

#SBATCH --mail-type=fail
#SBATCH --job-name="mapping"
#SBATCH --nodes=1
#SBATCH --cpus-per-task=4
#SBATCH --time=04:00:00
#SBATCH --mem=8G
#SBATCH --partition=pibu_el8

INPUT_DIR=/data/users/${USER}/rna_seq/fastqc
HISAT2_DIR=/containers/apptainer/hisat2_samtools_408dfd02f175cd88.sif

apptainer exec --bind $INPUT_DIR $HISAT2_DIR hisat2 -x <> -1 <> -2 <> -S <> -p 1