#!/bin/bash

#SBATCH --mail-type=fail
#SBATCH --job-name="indexing"
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=04:00:00
#SBATCH --mem=8G
#SBATCH --partition=pibu_el8

#save important directories as variables
INPUT_DIR=/data/users/${USER}/rna_seq/fastqc
HISAT2_DIR=/containers/apptainer/hisat2_samtools_408dfd02f175cd88.sif

#move to input directory
cd ${INPUT_DIR}

#unzip genome to allow for indexing
gunzip Mus_musculus.GRCm39.dna.primary_assembly.fa.gz

#index genome
apptainer exec --bind $INPUT_DIR $HISAT2_DIR hisat2-build Mus_musculus.GRCm39.dna.primary_assembly.fa ref_genome_index
