#!/bin/bash

#SBATCH --mail-type=fail
#SBATCH --job-name="mapping"
#SBATCH --nodes=1
#SBATCH --cpus-per-task=4
#SBATCH --time=12:00:00
#SBATCH --mem=8G
#SBATCH --partition=pibu_el8

#store input and output directory as variables
INPUT_DIR=/data/users/${USER}/rna_seq/cleaned_fastp
OUT_DIR=/data/users/${USER}/rna_seq/sam_files

#move to project directory and create output directory
cd /data/users/${USER}/rna_seq
mkdir ${OUT_DIR}

#initialize array to store file numbers
numbers=()

# Loop through the files and extract the numbers
for file in ${INPUT_DIR}/SRR*_*; do
  # Extract the filename without the path
  filename=$(basename "$file")
  # Extract the number using bash string manipulation
  number=${filename#SRR}   # Remove 'SRR' prefix
  number=${number%%_*}     # Remove everything after the first '_'

  # Check if the number is already in the unique_numbers array
  if [[ ! " ${numbers[@]} " =~ " ${number} " ]]; then
    numbers+=("$number")  # Add only if it's not already in the array
  fi
done

for number in "${numbers[@]}"; do
#submit 07a to the cluster for each entry in the numbers array
sbatch 07a_run_hisat2_mapping SRR${number}_1_cleaned.fastq.gz SRR${number}_2_cleaned.fastq.gz ${number}.sam
done
