#!/bin/bash

#SBATCH --mail-type=end,fail
#SBATCH --job-name="viewing"
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=02:00:00
#SBATCH --mem=4G
#SBATCH --partition=pibu_el8
#SBATCH --array=0-15
#SBATCH --output=/data/users/yjauslin/rna_seq/conversion.out

INPUT_DIR=/data/users/${USER}/rna_seq/sam_files
HISAT2_DIR=/containers/apptainer/hisat2_samtools_408dfd02f175cd88.sif
OUTPUT_DIR=/data/users/${USER}/rna_seq/bam_files

#move to project directory, create output directory and enter it
cd /data/users/${USER}/rna_seq
mkdir $OUTPUT_DIR
cd /data/users/${USER}/rna_seq/sam_files

#initialize array that stores file numbers
numbers=()

# Loop through the files and extract the numbers
for file in /data/users/${USER}/rna_seq/fastqc/SRR*_*; do
  # Extract the filename without the path
  filename=$(basename "$file")
  # Extract the number using bash string manipulation
  number=${filename#SRR}   # Remove 'SRR' prefix
  number=${number%%_*}     # Remove everything after the first '_'

  # Check if the number is already in the unique_numbers array
  if [[ ! " ${numbers[@]} " =~ " ${number} " ]]; then
    numbers+=("$number")  # Add only if it's not already in the array
  fi
done

#convert .sam files to .bam files
apptainer exec --bind $INPUT_DIR $HISAT2_DIR samtools view -hbS $INPUT_DIR/${numbers[$SLURM_ARRAY_TASK_ID]}.sam > ${OUTPUT_DIR}/${numbers[$SLURM_ARRAY_TASK_ID]}.bam
