#!/bin/bash

#SBATCH --mail-type=end,fail
#SBATCH --job-name="sorting"
#SBATCH --nodes=1
#SBATCH --cpus-per-task=4
#SBATCH --time=02:00:00
#SBATCH --mem=35G
#SBATCH --partition=pibu_el8
#SBATCH --array=0-15
#SBATCH --output=/data/users/yjauslin/rna_seq/sorting.out

#save important directories as variables
INPUT_DIR=/data/users/${USER}/rna_seq/bam_files
HISAT2_DIR=/containers/apptainer/hisat2_samtools_408dfd02f175cd88.sif
OUTPUT_DIR=/data/users/${USER}/rna_seq/sorted_bam

#move to project directory and create output directory
cd /data/users/${USER}/rna_seq
mkdir $OUTPUT_DIR

#initialize array to store file numbers
numbers=()

# Loop through the files and extract the numbers
for file in /data/users/${USER}/rna_seq/fastqc/SRR*_*; do
  # Extract the filename without the path
  filename=$(basename "$file")
  # Extract the number using bash string manipulation
  number=${filename#SRR}   # Remove 'SRR' prefix
  number=${number%%_*}     # Remove everything after the first '_'

  # Check if the number is already in the numbers array
  if [[ ! " ${numbers[@]} " =~ " ${number} " ]]; then
    numbers+=("$number")  # Add only if it's not already in the array
  fi
done

#sort input file and create sorted output file, -m = memory, -@ = number of threads to be used
apptainer exec --bind $INPUT_DIR $HISAT2_DIR samtools sort -m 30G -@ 4 -o ${OUTPUT_DIR}/${numbers[$SLURM_ARRAY_TASK_ID]}_sorted.bam -T temp ${INPUT_DIR}/${numbers[$SLURM_ARRAY_TASK_ID]}.bam
