#!/bin/bash

#SBATCH --mail-type=fail
#SBATCH --job-name="sorting"
#SBATCH --nodes=1
#SBATCH --cpus-per-task=4
#SBATCH --time=02:00:00
#SBATCH --mem=35G
#SBATCH --partition=pibu_el8

#save important directories as variables
INPUT_DIR=/data/users/${USER}/rna_seq/bam_files
HISAT2_DIR=/containers/apptainer/hisat2_samtools_408dfd02f175cd88.sif
OUTPUT_DIR=/data/users/${USER}/rna_seq/sorted_bam

#read in input and output file from the command line
INPUT_FILE=$1
OUTPUT_FILE=$2

#move to project directory and create output directory
cd /data/users/${USER}/rna_seq
mkdir $OUTPUT_DIR

#sort input file and create sorted output file
apptainer exec --bind $INPUT_DIR $HISAT2_DIR samtools sort -m 30G -@ 4 -o ${OUTPUT_DIR}/$OUTPUT_FILE -T temp ${INPUT_DIR}/$INPUT_FILE
