#!/bin/bash

#SBATCH --mail-type=fail
#SBATCH --job-name="viewing"
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=02:00:00
#SBATCH --mem=4G
#SBATCH --partition=pibu_el8

INPUT_DIR=/data/users/${USER}/rna_seq/sam_files
HISAT2_DIR=/containers/apptainer/hisat2_samtools_408dfd02f175cd88.sif
OUTPUT_DIR=/data/users/${USER}/rna_seq/bam_files

INPUT_FILE=$1
OUTPUT_FILE=$2

mkdir $OUTPUT_DIR
cd /data/users/${USER}/rna_seq/sam_files

apptainer exec --bind $INPUT_DIR $HISAT2_DIR samtools view -hbS $INPUT_FILE > ${OUTPUT_DIR}/$OUTPUT_FILE
