#!/bin/bash

#SBATCH --mail-type=fail
#SBATCH --job-name="indexing"
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=02:00:00
#SBATCH --mem=4G
#SBATCH --partition=pibu_el8

#save important directories as variables
INPUT_DIR=/data/users/${USER}/rna_seq/sorted_bam
HISAT2_DIR=/containers/apptainer/hisat2_samtools_408dfd02f175cd88.sif
OUTPUT_DIR=/data/users/${USER}/rna_seq/index_bam

#read in input and output file from the command line
INPUT_FILE=$1
OUTPUT_FILE=$2

#move to project directory and create output directory
cd /data/users/${USER}/rna_seq
mkdir $OUTPUT_DIR

#index sorted bam file
apptainer exec --bind $INPUT_DIR $HISAT2_DIR samtools index -o ${OUTPUT_DIR}/$OUTPUT_FILE ${INPUT_DIR}/$INPUT_FILE
