#!/bin/bash

#SBATCH --mail-type=fail
#SBATCH --job-name="indexing"
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=02:00:00
#SBATCH --mem=4G
#SBATCH --partition=pibu_el8

INPUT_DIR=/data/users/${USER}/rna_seq/sorted_bam
HISAT2_DIR=/containers/apptainer/hisat2_samtools_408dfd02f175cd88.sif
OUTPUT_DIR=/data/users/${USER}/rna_seq/index_bam

cd /data/users/${USER}/rna_seq
mkdir $OUTPUT_DIR

numbers=()

# Loop through the files and extract the numbers
for file in /data/users/${USER}/rna_seq/fastqc/SRR*_*; do
  # Extract the filename without the path
  filename=$(basename "$file")
  # Extract the number using bash string manipulation
  number=${filename#SRR}   # Remove 'SRR' prefix
  number=${number%%_*}     # Remove everything after the first '_'

  # Check if the number is already in the unique_numbers array
  if [[ ! " ${numbers[@]} " =~ " ${number} " ]]; then
    numbers+=("$number")  # Add only if it's not already in the array
  fi
done

for number in "${numbers[@]}"; do
apptainer exec --bind $INPUT_DIR $HISAT2_DIR samtools index -o ${OUTPUT_DIR}/${number}_indexed.bam.bai ${INPUT_DIR}/${number}_sorted.bam
done