#!/bin/bash

#SBATCH --mail-type=fail
#SBATCH --job-name="edit_fcounts"
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=00:05:00
#SBATCH --mem=1G
#SBATCH --partition=pibu_el8


File=$1

tail -n +2 $File | cut --fields=1,7- > counts_filtered.txt