#!/bin/bash

#SBATCH --mail-type=fail
#SBATCH --job-name="featCounts"
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=03:00:00
#SBATCH --mem=1G
#SBATCH --partition=pibu_el8

INPUT_DIR=/data/users/${USER}/rna_seq/sorted_bam
CONTAINER_DIR=/containers/apptainer/subread_2.0.1--hed695b0_0.sif

#move to project directory
cd /data/users/${USER}/rna_seq

#unzip annotation of reference genome
gunzip /data/users/${USER}/rna_seq/fastqc/Mus_musculus.GRCm39.113.gtf.gz

#give permission to the input files
chmod +wrx $INPUT_DIR/*.bam

apptainer exec --bind $INPUT_DIR $CONTAINER_DIR featureCounts -p -s 2 -a /data/users/${USER}/rna_seq/fastqc/Mus_musculus.GRCm39.113.gtf -o counts.txt $INPUT_DIR/*.bam

gzip /data/users/${USER}/rna_seq/fastqc/Mus_musculus.GRCm39.113.gtf

tail -n +2 counts.txt | cut --fields=1,7- > counts_filtered.txt